// Select title input field
const titleElement = document.querySelector('#product-title')
// Why querySelector('#id')?
// → Fastest & most reliable way to target a unique element by its id
// → id selectors are very performant in modern browsers
// → Avoids ambiguity if other inputs exist on the page

// Select price input field
const priceElement = document.querySelector('#product-price')
// Same reason — consistent, readable, and efficient DOM access
// Using variables instead of repeating querySelector improves performance & clarity

// Select remove button
const removeElement = document.querySelector('#remove-product')
// Why separate variable?
// → Makes event listener code cleaner & more readable
// → Reusable if you need to reference the button multiple times

// Select the span where last edit message will be shown
const dateElement = document.querySelector('#last-edit')
// Why querySelector here?
// → Allows dynamic update of the "Last Edit: ..." text
// → id ensures we target the correct element reliably

// Extract product ID from URL hash
// Example: edit-product.html#abc123 → productId = "abc123"
const productId = location.hash.substring(1)
// Why location.hash + substring(1)?
// → Simple, client-side way to pass the product ID without query params (?id=) or backend
// → Works perfectly with static HTML files — no server routing needed
// → Common vanilla JS pattern for "routing" in multi-page apps
// → Hash changes don't trigger full page reload

// Load all saved products from localStorage using shared helper
let products = getSaveProducts()
// Why let (not const)?
// → products will be reassigned later when the 'storage' event fires
// → Allows the edit page to stay in sync if someone changes products in another tab

// Find the specific product we want to edit
let product = products.find(item => {
    return item.id === productId
    // Relies on each product having a unique .id (generated by uuidv4())
})

// Safety check: if product not found (deleted or invalid ID) → redirect
if (product === undefined) {
    location.assign('/index.html')
    // Why location.assign()?
    // → Adds current page to browser history → user can press back if needed
    // → Prevents staying on a broken/blank edit page
    // → Good error handling & user experience
}

// Pre-fill form fields with current product data
titleElement.value = product.title
// Why .value = ... ?
// → Populates input with existing title → user can see and edit current value

priceElement.value = product.price
// Same idea — auto-converts number to string if needed (safe for text input)

// Display relative last edit time in Persian
dateElement.textContent = lastEditMessage(product.updated)
// Why call lastEditMessage()?
// → Generates user-friendly message like "آخرین ویرایش: ۵ دقیقه پیش"
// → Uses jalali-moment for Persian relative time
// → Updates dynamically — shows how recently the product was modified

// Auto-save title on every change
titleElement.addEventListener('input', (e) => {
    product.title = e.target.value
    product.updated = moment().valueOf()
    // Why update .updated timestamp?
    // → Records when the edit happened → accurate "last edit" time
    // → Uses moment().valueOf() → milliseconds since 1970 (numeric, sortable)
    saveProducts(products)
    // Why 'input' event?
    // → Captures every keystroke/paste → real-time saving
    // → No "Save" button needed → modern, low-friction UX
    // Why saveProducts() every time?
    // → Immediate persistence → survives refresh/close
    // → Triggers 'storage' event → syncs other tabs/windows
})

// Auto-save price on every change
priceElement.addEventListener('input', (e) => {
    product.price = e.target.value
    product.updated = moment().valueOf()
    // Same timestamp update as title → keeps last edit accurate
    saveProducts(products)
    // Same real-time save pattern as title
    // Note: price is stored as string → later you can parseFloat() if needed
})

// Delete product when remove button is clicked
removeElement.addEventListener('click', (e) => {
    removeProduct(product.id)
    // Calls shared removeProduct() from function.js → removes by id
    saveProducts(products)
    // Persist deletion immediately → other tabs see it gone
    location.assign('./index.html')
    // Redirect back to list → user sees updated list right away
    // Why ./index.html (relative path)?
    // → Works if edit-product.html is in the same folder as index.html
    // → /index.html (absolute) also fine — both correct here
})

// Listen for changes made in other tabs/windows
window.addEventListener('storage', (e) => {
    if (e.key === 'products') {
        products = JSON.parse(e.newValue)
        // Why re-parse e.newValue?
        // → storage event delivers new value as string → must convert back to array
        // → Keeps local products variable up-to-date

        // Re-find product (in case it was deleted/edited elsewhere)
        product = products.find(item => {return item.id === productId })

        if (product === undefined) {
            location.assign('/index.html')
            // If product was removed on another tab → redirect to list
            // Prevents editing non-existent item → good safety
        }

        // Update form fields with latest data
        titleElement.value = product.title
        priceElement.value = product.price
        // Why update inputs?
        // → If someone else edits the same product in another tab → see live changes
        // → True multi-tab synchronization via browser's storage event
    }
})