// Quick test / demo line (can be removed later)
// Why console.log(uuidv4()) ?
// → Tests whether the uuid library is properly included and working
// → uuidv4() generates a random UUID (version 4) → perfect for unique product IDs
// → Helps confirm before using it in product creation
// → Will throw ReferenceError if no uuid script is loaded in HTML
console.log(uuidv4())

// Helper: Load products from localStorage or return empty array
const getSaveProducts = function() {
    // Attempt to load previously saved products
    const productJSON = localStorage.getItem('products')
    
    // Why check !== null ?
    // → localStorage.getItem returns null when no data was ever saved
    //   (first visit, cleared storage, private browsing, etc.)
    // → JSON.parse(null) would throw SyntaxError → this guard prevents crash
    if (productJSON !== null) {
        return JSON.parse(productJSON)
        // Why JSON.parse?
        // → Converts stored JSON string back to real JavaScript array of objects
        // → After this → products has .id, .title, .exist properties usable
    } else {
        return []
        // Why return [] instead of undefined/null?
        // → Consistent type (always array) → safer for .push(), .find(), etc.
        // → Avoids extra null checks in calling code
    }
}

// Helper: Save products array to localStorage
const saveProducts = function(products) {
    // Why JSON.stringify?
    // → localStorage only stores strings → this turns array into valid JSON
    // → Without it → saves useless "[object Object]" strings
    localStorage.setItem('products', JSON.stringify(products))
    
    // Why no try/catch?
    // → Kept simple for learning → errors are rare in local dev
    // → In real apps: add try/catch for quota exceeded or security blocks
}

// Remove a product by its unique id
const removeProduct = function(id) {
    // Find position of product with matching id
    // Why .findIndex()?
    // → Returns number (index) → perfect for .splice()
    // → .find() would return object → harder to remove from array
    const productIndex = products.findIndex(function(item) {
        return item.id === id
        // Assumes every product has .id (generated by uuidv4())
    })
    
    // Why check > -1 ?
    // → .findIndex returns -1 if no match → .splice(-1) would be invalid
    if (productIndex > -1) {
        products.splice(productIndex, 1)
        // Removes exactly one item at that index
        // Mutates array directly → changes visible everywhere
    }
    // No return value → side-effect function (modifies global products)
}

// New: Toggle the 'exist' property of a product by id
const toggleProduct = function(id) {
    // Find the product object by id
    // Why .find() instead of .findIndex() here?
    // → We want the object itself to modify its .exist property
    const product = products.find(function(item) {
        return item.id === id
    })
    
    // Why check !== undefined ?
    // → Prevents error if id not found (though unlikely with proper buttons)
    if (product !== undefined) {
        product.exist = !product.exist
        // Toggles boolean: true → false, false → true
        // Simple inversion → no need for if/else
    }
}

// Main rendering function: filters → clears → rebuilds DOM
const renderProducts = function(products, filters) {
    // First filter: case-insensitive title search
    // Why .toLowerCase() on both?
    // → Users expect "book" to match "Book", "BOOK", etc.
    let filteredProducts = products.filter(function(item) {
        return item.title.toLowerCase().includes(filters.searchItem.toLowerCase())
    })

    // Second filter: available products only if checkbox checked
    // Why separate?
    // → Readable, debuggable, easy to add more filters later
    filteredProducts = filteredProducts.filter(function(item) {
        if (filters.availableProducts) {
            return item.exist   // boolean return is clean & idiomatic
        } else {
            return true         // show all
        }
    })
    
    // Clear previous items
    // Why innerHTML = '' ?
    // → Fastest way to remove all children
    // → Prevents duplicates on re-render
    document.querySelector('#products').innerHTML = ''
    
    filteredProducts.forEach(function(item) {
        document.querySelector('#products').appendChild(createProductDOM(item))
    })
}

// Helper: Build DOM for one product (with checkbox toggle + remove)
const createProductDOM = function(product) {
    const productEl = document.createElement('div')
    const checkbox = document.createElement('input')
    const productItem = document.createElement('a')
    const removeButton = document.createElement('button')

    checkbox.setAttribute('type', 'checkbox')
    // Why checkbox.checked = !product.exist ?
    // → If exist = true (available) → checkbox unchecked (not "unavailable")
    // → If exist = false → checkbox checked (marks as unavailable)
    // → Visual representation matches the state
    checkbox.checked = !product.exist
    productEl.appendChild(checkbox)

    // Wire up toggle on change
    // Why here inside createProductDOM?
    // → Each checkbox gets its own listener with closure over current product.id
    // → No need for event delegation or data-id attributes
    checkbox.addEventListener('change', function(e) {
        toggleProduct(product.id)
        saveProducts(products)          // persist the toggle immediately
        renderProducts(products, filters) // refresh UI
    })

    productItem.textContent = product.title
    productItem.setAttribute('href', `./edit-product.html#${product.id}`)
    productEl.appendChild(productItem)

    removeButton.textContent = 'Remove'
    productEl.appendChild(removeButton)
    
    // Wire up remove button
    // Why addEventListener here?
    // → Each button knows exactly which product.id to remove (via closure)
    // → Clean, no global event listeners needed
    removeButton.addEventListener('click', function() {
        removeProduct(product.id)
        saveProducts(products)          // save after removal
        renderProducts(products, filters) // refresh list
    })
    
    return productEl
}